### ISSUE TITLE
Windows: QEMU: Process cannot access the file, being used by another process

### ISSUE THREAD

**Issue by araspik** [Richard-W/uefi-run#1] opened 2019-03-10 10:33 UTC
Running `QEMU` via `OVMF` on Windows 10.
```
C:\Program Files\qemu\qemu-system-x86_64.exe: -drive file=C:\Users\USER~1\AppData\Local\Temp\.tmpxIl4Iq,index=0,media=disk,format=raw: Could not open 'C:\Users\USER~1\AppData\Local\Temp\.tmpxIl4Iq': The process cannot access the file because it is being used by another process.
qemu execution failed
```
Is it possible to instead produce the output and save it so that the user can manually run QEMU on it?

**Comment by richard-w** [comment] 2019-03-11 16:14
I can not really reproduce this since I do not have a development environment on Windows. Can you clone the repo and test whether your issue is fixed on the "fix/windows-imagefile-lock" branch?

If this solves your issue I'll release the fix.

**Comment by richard-w** [comment] 2019-03-12 08:29
I checked that only qemu holds a handle on the image using `lsof`. Version 0.3.1 has been released with the fix included. It should work now on Windows. Reopen this if the issue is not fixed.

**Closed as completed by richard-w** 2019-03-12 08:29 UTC

**Comment by araspik** [comment] 2019-03-12 19:44
Yup, works now. Thanks!
